# Generated by Django 4.0.2 on 2022-02-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to='Users/apple/Desktop/FileUpload/'),
        ),
    ]
